# -*- coding: utf-8 -*-
"""merkle2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HB_9MgBl_jy-30VPgkzwDKdiFEvu5aL
"""

import hashlib, random

h=lambda x:hashlib.sha256(x.encode()).hexdigest()
#Genera entero aleatorio para simular transacciones (soporta hasta 100.000)
a=[h(str(random.randint(10**9,10**10-1))) for _ in range(int(input("N: ")))]
#Bucle hasta que quede solo la raiz
while len(a)>1:
    if len(a)%2: #Si es impar duplica el último elemento
        a.append(a[-1])
    a=[h(a[i]+a[i+1]) for i in range(0,len(a),2)] #Concatena

print("Merkle Root:",a[0])

import hashlib

h=lambda x:hashlib.sha256(x.encode()).hexdigest()
n=int(input("N: "))
t=[input(f"T{i+1}: ") for i in range(n)]
a=[h(x) for x in t] #Conversión a sha-256
niveles=[]

while len(a)>1:
    if len(a)%2:
        a.append(a[-1])
    niveles.append(a.copy()) #La primera copia se guarda dentro del ciclo para mostrar los elementos duplicados
    a=[h(a[i]+a[i+1]) for i in range(0,len(a),2)]

niveles.append(a.copy())
print("Merkle Root:",a[0])

for i,nivel in enumerate(niveles):
    print(f"\nNivel {i}:")
    print("   ".join(x[:8] for x in nivel)) #Se muestran solo los 8 primeros digitos de cada hash

i=int(input(f"Transacción a evaluar (1-{len(t)}): "))-1
x=input("Escriba la transacción: ")
p=h(x)
pos=i

for nivel in niveles[:-1]: #Recorre los niveles desde arriba hacia abajo (no incluye el último nivel)
    hermano=pos^1 #Hace una operación en la cual si la posición es par su hermano sera el impar siguiente y si es impar el par anterior
    if hermano>=len(nivel):  #Si los bloques son impares, el ultimo bloque se emparejara consigo mismo
        hermano=pos
    #Dependiendo si es par o impar hace A+B o B+A siendo p=a y su hermano=b
    if pos%2==0:
        p=h(p+nivel[hermano])
    else:
        p=h(nivel[hermano]+p)
    pos//=2
if p==niveles[-1][0]:
    print("VÁLIDA")
else:
    print("NO VÁLIDA")